version: '2'
services:
  ubuntujenkins:
    image: jenkins:2.0
    links:
      - mysql:mysql
    ports:
      - 8080:8080
  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_DATABASE=toto
      - MYSQL_USER=ic06
      - MYSQL_PASSWORD=ic06
      - MYSQL_ROOT_PASSWORD=ic06

